sonar.projectKey=clavepui-webhook
sonar.projectName=ClavePUI Webhook
sonar.projectVersion=1.0

# Ruta del código fuente
sonar.sources=src
sonar.exclusions=node_modules/**,tests/**

# Idioma
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Conexión a SonarQube local
sonar.host.url=http://localhost:9000
sonar.token=sqp_354e3ce37b9cb4c711032e683b8e5f4ab0ef9eee